# Adjacency List

In [1]:
class AdjNode:
    def __init__(self, data):
        self.vertex = data
        self.next = None

In [2]:
class Graph:
    def __init__(self, vertices):
        self.V = vertices
        self.graph = [None] * self.V
        
    def addEdge(self, origin, destination):
        node = AdjNode(destination)
        node.next = self.graph[origin]
        self.graph[origin] = node
        
        node = AdjNode(origin)
        node.next = self.graph[destination]
        self.graph[destination] = node
        
    def display(self):
        for i in range(self.V):
            print(f"vertex {i}:", end="")
            temp = self.graph[i]
            
            while temp:
                print(f" -> {temp.vertex}", end="")
                temp = temp.next
            print()
    

In [3]:
vertex_count = 5
graph = Graph(vertex_count)

graph.addEdge(0, 1)
graph.addEdge(0, 4)
graph.addEdge(1, 2)
graph.addEdge(1, 3)
graph.addEdge(1, 4)
graph.addEdge(2, 3)
graph.addEdge(3, 4)

In [4]:
graph.display()

vertex 0: -> 4 -> 1
vertex 1: -> 4 -> 3 -> 2 -> 0
vertex 2: -> 3 -> 1
vertex 3: -> 4 -> 2 -> 1
vertex 4: -> 3 -> 1 -> 0


# Adjacency Matrix

In [34]:
import numpy as np

class GraphAdjMat:
    def __init__(self, number_of_vertex):
        self.vertex = number_of_vertex
        self.data = np.zeros((self.vertex, self.vertex))
        
    def addEdge(self, origin, destination, weight=1,  direct=False):
        if origin >= self.vertex or destination >= self.vertex:
            print("Index tidak benar,input nilai index antara 0 dan", self.vertex - 1)
            return
        
        if direct == "direct":
            self.data[origin][destination] = weight
        else:
            self.data[origin][destination] = weight
            self.data[destination][origin] = weight
            
            # self.data[origin][destination] = self.data[destination][origin] = weight
            
    def display(self):
        print(self.data)
        
    def countVertex(self):
        return self.vertex
    
    def countEdge(self):
        edge = 0
        for i in range(self.vertex):
            for j in range(self.vertex):
                if self.data[i][j] != 0:
                    edge += 1
                    
        return edge
    
    def removeEdge(self, origin, destination, direct=False):
        if origin >= self.vertex or destination >= self.vertex:
            print("Index tidak benar,input nilai index antara 0 dan", self.vertex - 1)
            return
        if direct == "direct":
            self.data[origin][destination] = 0
        else:
            self.data[origin][destination] = 0
            self.data[destination][origin] = 0
            
    def addVertex(self):
        n = self.vertex
        new_data = np.zeros((self.vertex + 1, self.vertex + 1))
        for i in range(n):
            for j in range(n):
                new_data[i][j] = self.data[i][j]
        self.data = new_data
        self.vertex += 1

In [37]:
count_vertex = 5
graph = GraphAdjMat(count_vertex)
graph.addEdge(0, 1)
graph.addEdge(0, 4)

# graph.display()

print("Jumlah vertex:", graph.countVertex())
print("Jumlah edge:", graph.countEdge())

print()
graph.removeEdge(0, 1)
# graph.display()

print()
graph.addVertex()
graph.display()

print()
graph.addEdge(1, 3, 5)
graph.addEdge(0, 2, 7)
graph.display()

print("Jumlah vertex:", graph.countVertex())
print("Jumlah edge:", graph.countEdge())

Jumlah vertex: 5
Jumlah edge: 4


[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 7. 0. 1. 0.]
 [0. 0. 0. 5. 0. 0.]
 [7. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Jumlah vertex: 6
Jumlah edge: 6
